
NUM_WORKERS: 10
BATCH_SIZE: 100
LR_EPOCHS: [20, 30, 40, 50]
LR_DECAY: 0.2
INITIAL_LR: 0.01
WEIGHTS_DECAY: 0.00001
EPOCHS_PER_TASK: 50
TASK_SIZE: 2
K: 100
TOTAL_CLASSES: 10
NUM_CLASSES: 2
DATASET: 'cifar10'
SEED: 0

SAVE_PATH: "./results/"
DEVICE: torch.device("cuda:0")
